DATA_PKT_IDENTIFIER = 0b0101010101010101

SEQ_OFFSET = 0
SEQ_LEN = 4

CHKSUM_LEN = 2
CHKSUM_OFFSET = SEQ_OFFSET + SEQ_LEN

DATAID_OFFSET = CHKSUM_OFFSET+CHKSUM_LEN
DATAID_LEN = 2

DATA_OFFSET = DATAID_OFFSET + DATAID_LEN

TERMINATOR = '\x03'*3

TIME_OUT = 0.5 #secs